### ISSUE TITLE
Write URL to access server to console

### ISSUE THREAD

**Issue by starblue** [thecoshman/http#127] opened 2021-02-03 09:50 UTC
Can you write an URL to access the server to the console during startup? Other local servers do that, for example Jekyll or `wasm-pack test`, and modern terminals support clicking on that URL to open a browser window.

**Comment by cyqsimon** [comment] 2021-02-03 10:56
+1
I like the way [`http-server`](https://www.npmjs.com/package/http-server) does it, printing all potentially useful URLs:

![Screencap-001-20210203-185422](https://user-images.githubusercontent.com/28627918/106737237-66528400-6651-11eb-8992-630801173180.png)

**Comment by nabijaczleweli** [comment] 2021-02-03 12:37
Dupe of #10 and #106.

**Closed by nabijaczleweli** 2021-02-03 12:37 UTC
Labels: duplicate

**Comment by starblue** [comment] 2021-02-03 12:52
It is different from #10, which copied the details to the clipboard. That functionality was removed, because it added too much complexity (rightly so).

Printing URLs to the console is much easier, if there are hard cases you can just skip those.

**Comment by nabijaczleweli** [comment] 2021-02-03 13:14
Indeed, and since I cannot guarantee any of them will work, I skip all of them. I urge you to consider what good printing fifteen useless lines, one or two of which has the potential to work, and only in a few contexts, would do.

**Comment by cyqsimon** [comment] 2021-02-05 08:10
@nabijaczleweli The reason I support this idea is that at the end of the day, any software should serve its users' needs, not dismiss them for petty technical reasons. Since `http` is first and foremost a quick-and-dirty file server, convenience is pretty high up on the list of evaluation criteria. Printing the list of available addresses for the user contributes to convenience quite significantly IMO.

I for example, often find myself running `httplz` in a terminal window on my laptop to share a file, then remembering I should have run `ipconfig`/`ifconfig` beforehand to get my LAN address first.

We don't need to make sure every address we print in usable; just providing some information is enough. The user can decide which one they actually want. If the user decides to change their network configuration while `http` is running, then it's none of our business. Nor do we really need to care about DNS stuff because again, `http` is primarily advertised as a development/test server.

In terms of cross-platform compatibility, I think [this crate](https://crates.io/crates/get_if_addrs) is an easy way to grab a list of addresses. I will give it a try in my fork.

**Comment by starblue** [comment] 2021-02-05 09:01
Since I use it locally on my machine (I was working through [WASM by Example](https://wasmbyexample.dev/)) I would already be happy if the info printed at the start (configured IP address and port) could be rendered as an URL.
IMHO it would also be more secure if the default were to listen only on localhost (I assumed that initially), but unfortunately you can't change that now without breaking backward compatibility.

**Comment by cyqsimon** [comment] 2021-02-05 14:33
@starblue Can you please help test [my fork](https://github.com/cyqsimon/http)? The commits are on branch [existing_opt](https://github.com/cyqsimon/http/tree/existing_opt). Thanks.

**Comment by starblue** [comment] 2021-02-10 10:47
Sorry for the delay, I now tested it.

It's somewhat helpful (for me it is OK), but not all of the listed addresses work, which might confuse people.

It always lists the same four addresses:
```
Available on:
	http://127.0.0.1:8000
	http://[::1]:8000
	http://10.158.2.34:8000
	http://10.158.2.28:8000
```
The last two are Wifi and wired Ethernet.

If I don't specify an address it listens on the IPv4 addresses, but not on the IPv6 loopback address.
If I specify the IPv6 default address by `-a '::'`, it listens on all addresses.
Otherwise it listens only on the specified address.

Wifi and LAN were tested from another computer.
