### ISSUE TITLE
Add support for renaming files/folders

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#92] opened 2019-09-18 08:45 UTC
If there's an RFC that defines how a 'rename' method should work, I guess follow that.

Failing that, we can just use a `RENAME` method, or if people are scared of using wild crazy new methods, we can use `PATCH`.

The resources in the URI would be the resource being renamed, obviously. Then maybe use a header for the new name. The `RENAME` method could just put it in the body, `PATCH` would need a more structured way of handling it.

**Comment by nabijaczleweli** [comment] 2019-09-18 12:53
Closing as duplicate of #61

**Closed by nabijaczleweli** 2019-09-18 12:53 UTC
Labels: feature

**Comment by thecoshman** [comment] 2019-09-18 16:06
Assuming we have full WebDAV support... then I guess you could argue this a duplicate. Adding support for rename is a lot simpler than full WebDAV support though, and I don't particularly see much need to push for use of WebDAV

**Comment by nabijaczleweli** [comment] 2019-09-18 16:45
WebDAV supports COPY and MOVE in a standard fashion, and I'm not boutta write an RFC v0v

**Comment by thecoshman** [comment] 2019-09-19 09:11
I'm not saying _write_ an RFC for a proper HTTP 'rename' verb, but if there is one, use it. Else we can just roll our own. 
In theory, our own server can support whatever verbs it wants to and our own client can thus make use of them.
Shit will probably start to break though with bad servers sitting in the middle _thinking_ they are correct dropping requests with 'bad' verbs. 

What's the sort of timeline that you're expecting for WebDAV support though?

**Comment by nabijaczleweli** [comment] 2019-09-19 12:36
I've mostly cracked the code, so a week? maybe, if nothing comes up and porting goes well.

**Comment by thecoshman** [comment] 2019-09-19 12:38
:O cracker!

Alright... and then there's issue #93 that has been raised for the UI to expose these options/controls. Grand so, this can stay closed.
